apiVersion: v1
kind: Pod
metadata:
  name: annotations
  labels:
    environment: dev
    project: roboshop
    component: frontend
  annotations:
    imageregistry: "https://hub.docker.com/"
    jenkinsURL: "https://jenkins.joindevops.com/build/job/roboshop/34"
spec:
  containers:
  - name: nginx
    image: nginx